set(source_list ${source_list}
${PROJ_PATH}/Application/Inc/lwshell/lwshell.c
${PROJ_PATH}/Application/Src/ADC.cpp
${PROJ_PATH}/Application/Src/CLI.cpp
${PROJ_PATH}/Application/Src/DAC.cpp
${PROJ_PATH}/Application/Src/Flash_STM32G431KB.cpp
${PROJ_PATH}/Application/Src/GPIO.cpp
${PROJ_PATH}/Application/Src/LED.cpp
${PROJ_PATH}/Application/Src/main.cpp
${PROJ_PATH}/Application/Src/SerialCOM.cpp
${PROJ_PATH}/Application/Src/Thread.cpp
${PROJ_PATH}/Core/Src/adc.c
${PROJ_PATH}/Core/Src/dac.c
${PROJ_PATH}/Core/Src/dma.c
${PROJ_PATH}/Core/Src/gpio.c
${PROJ_PATH}/Core/Src/stm32g4xx_hal_msp.c
${PROJ_PATH}/Core/Src/stm32g4xx_hal_timebase_tim.c
${PROJ_PATH}/Core/Src/stm32g4xx_it.c
${PROJ_PATH}/Core/Src/syscalls.c
${PROJ_PATH}/Core/Src/system_stm32g4xx.c
${PROJ_PATH}/Core/Src/tim.c
${PROJ_PATH}/Core/Src/usart.c
${PROJ_PATH}/Core/startup_stm32g431xx.s
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dac.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dac_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c
${PROJ_PATH}/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/croutine.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/list.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/queue.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/tasks.c
${PROJ_PATH}/Middlewares/Third_Party/FreeRTOS/Source/timers.c
)
