name: "Build Binary"
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Skip_Checking:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5

  Github-Build:
    runs-on: ubuntu-latest
    needs: Skip_Checking
    if: needs.Skip_Checking.outputs.should_skip != 'true'
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y \
            	build-essential \
              gcc-arm-none-eabi \
              binutils-arm-none-eabi \
              cmake ninja-build \
              git \
              stlink-tools \
              xz-utils curl

      - name: Checkout Files
        uses: actions/checkout@v4

      - name: Build Init
        run: cmake -DCMAKE_BUILD_TYPE=Release "-B $GITHUB_WORKSPACE/build" -G Ninja

      - name: Build
        run: cmake --build $GITHUB_WORKSPACE/build -j 10

  Alpine-Build:
    runs-on: ubuntu-latest
    needs: Skip_Checking
    if: needs.Skip_Checking.outputs.should_skip != 'true'
    container:
      image: "ghcr.io/jasonyang-ee/stm32-builder:alpine-latest"
    steps:
      - uses: actions/checkout@v4
      - name: BUILD
        run: build.sh

  Arch-Build:
    runs-on: ubuntu-latest
    needs: Skip_Checking
    if: needs.Skip_Checking.outputs.should_skip != 'true'
    container:
      image: "ghcr.io/jasonyang-ee/stm32-builder:arch-latest"
    steps:
      - uses: actions/checkout@v4
      - name: BUILD
        run: build.sh

  Ubuntu-Build-Upload:
    runs-on: ubuntu-latest
    needs: Skip_Checking
    if: needs.Skip_Checking.outputs.should_skip != 'true'
    container:
      image: "ghcr.io/jasonyang-ee/stm32-builder:ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: BUILD
        run: build.sh

      - name: Upload Binary .elf
        uses: actions/upload-artifact@v4
        with:
          name: BINARY.elf
          path: ${{ github.workspace }}/build/*.elf

      - name: Upload Binary .bin
        uses: actions/upload-artifact@v4
        with:
          name: BINARY.bin
          path: ${{ github.workspace }}/build/*.bin

  Result:
    runs-on: ubuntu-latest
    needs:
      - github-build
      - arch-build
      - alpine-build
      - ubuntu-build-upload
      - Skip_Checking
    if: always() && needs.Skip_Checking.outputs.should_skip != 'true'
    steps:
      - name: All Tests Ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some Tests Failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1